import './globals.css'
import type { Metadata } from 'next'
import Providers from './Providers'
import { Header } from '@/infra/components/Header'
import Navbar from '@/infra/components/Navbar'

export const metadata: Metadata = {
  title: 'IMD Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <Navbar />
          {children}
        </Providers>
      </body>
    </html >
  )
}
